hotkeys:
  new: "ctrl+a"
  delete: "backspace"
  edit: "space"
  record_modal:
    new_split: "ctrl+a"
    new_paid_split: "ctrl+s"
    delete_last_split: "ctrl+d"
  categories:
    new_subcategory: "ctrl+s"
