hotkeys:
  new: "a"
  delete: "d"
  edit: "e"
  toggle_jump_mode: "v"
  home:
    new_transfer: "t"
    toggle_splits: "s"
    display_by_date: "q"
    display_by_person: "w"
    cycle_offset_type: "."
    toggle_income_mode: "/"
    select_prev_account: "["
    select_next_account: "]"
    insights:
      toggle_use_account: '\'
  record_modal:
    new_split: "ctrl+a"
    new_paid_split: "ctrl+s"
    delete_last_split: "ctrl+d"
  categories:
    new_subcategory: "s"
symbols:
  line_char: "│"
  finish_line_char: "╰"
  split_paid: "✓"
  split_unpaid: "⨯"
  category_color: "●"
  amount_positive: "+"
  amount_negative: "-"
